install:
  - set QTDIR="C:\Qt\5.12.2\mingw73_64"
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%
  - set HAMLIBDIR="hamlib-w64-3.3"
  - set POSTGRESQLDIR="C:\Program Files\PostgreSQL\10"
  - ps: Start-FileDownload 'https://github.com/Hamlib/Hamlib/releases/download/3.3/hamlib-w64-3.3.zip'
  - 7z x hamlib-w64-3.3.zip
before_build:
  - qmake INCLUDEPATH+="%HAMLIBDIR%/include" LIBS+="-L%HAMLIBDIR%/lib/gcc" -config release QLog.pro
build_script:
  - mingw32-make
after_build:
  - windeployqt --release release/qlog.exe
  - xcopy %HAMLIBDIR%\bin\libhamlib-2.dll release\
  - xcopy %HAMLIBDIR%\bin\libusb-1.0.dll release\
  - xcopy %POSTGRESQLDIR%\bin\libpq.dll release\
  - xcopy %POSTGRESQLDIR%\bin\libeay32.dll release\
  - xcopy %POSTGRESQLDIR%\bin\libiconv-2.dll release\
  - xcopy %POSTGRESQLDIR%\bin\libintl-8.dll release\
  - xcopy %POSTGRESQLDIR%\bin\ssleay32.dll release\
  - rm release/*.o
  - rm release/*.cpp
artifacts:
  - path: release
    type: zip
