install:
  - set QTDIR="C:\Qt\5.13\mingw73_64"
  - set QTINSTALLERDIR="C:\Qt\Tools\QtInstallerFramework\3.1"
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%QTINSTALLERDIR%\bin;%PATH%
  - set HAMLIBDIR="hamlib-w64-3.3"
  - set OPENSSLDIR="C:\OpenSSL-v111-Win64"
  - set PACKAGEDIR="installer\packages\de.dl2ic.qlog\data"
  - ps: Start-FileDownload 'https://github.com/Hamlib/Hamlib/releases/download/3.3/hamlib-w64-3.3.zip'
  - 7z x hamlib-w64-3.3.zip
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
before_build:
  - qmake INCLUDEPATH+="%HAMLIBDIR%/include" LIBS+="-L%HAMLIBDIR%/lib/gcc" -config release QLog.pro
build_script:
  - mingw32-make
after_build:
  - xcopy release\qlog.exe %PACKAGEDIR%\
  - windeployqt --release %PACKAGEDIR%\qlog.exe
  - xcopy %OPENSSLDIR%\bin\libssl-1_1-x64.dll %PACKAGEDIR%\
  - xcopy %OPENSSLDIR%\bin\libcrypto-1_1-x64.dll %PACKAGEDIR%\
  - xcopy %OPENSSLDIR%\bin\capi.dll %PACKAGEDIR%\
  - xcopy %OPENSSLDIR%\bin\dasync.dll %PACKAGEDIR%\
  - xcopy %OPENSSLDIR%\bin\ossltest.dll %PACKAGEDIR%\
  - xcopy %OPENSSLDIR%\bin\padlock.dll %PACKAGEDIR%\
  - xcopy %HAMLIBDIR%\bin\libhamlib-2.dll %PACKAGEDIR%\
  - xcopy %HAMLIBDIR%\bin\libusb-1.0.dll %PACKAGEDIR%\
  - xcopy %POSTGRESQLDIR%\bin\libpq.dll %PACKAGEDIR%\
  - xcopy %POSTGRESQLDIR%\bin\libeay32.dll %PACKAGEDIR%\
  - xcopy %POSTGRESQLDIR%\bin\libiconv-2.dll %PACKAGEDIR%\
  - xcopy %POSTGRESQLDIR%\bin\libintl-8.dll %PACKAGEDIR%\
  - xcopy %POSTGRESQLDIR%\bin\ssleay32.dll %PACKAGEDIR%\
  - binarycreator.exe -f -c installer\config\config.xml -p installer\packages qlog-installer.exe
artifacts:
  - name: installer
    path: qlog-installer.exe
deploy:
- provider: S3
  access_key_id: AKIAXYSRXXQSSBOIRSWX
  secret_access_key:
    secure: OglRX95dO8sX52fJvZGBGmspHOXM1fDg/i6kaJLhmUBu1BVwi3tH13v9OCB3TB/i
  region: eu-central-1
  bucket: qlog.dl2ic.de
  folder: build
  artifact: installer
  set_public: true
